// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: speaker.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SpeakerClient is the client API for Speaker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SpeakerClient interface {
	Speak(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type speakerClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeakerClient(cc grpc.ClientConnInterface) SpeakerClient {
	return &speakerClient{cc}
}

func (c *speakerClient) Speak(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/interceptor.Speaker/Speak", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeakerServer is the server API for Speaker service.
// All implementations must embed UnimplementedSpeakerServer
// for forward compatibility
type SpeakerServer interface {
	Speak(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedSpeakerServer()
}

// UnimplementedSpeakerServer must be embedded to have forward compatible implementations.
type UnimplementedSpeakerServer struct {
}

func (UnimplementedSpeakerServer) Speak(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Speak not implemented")
}
func (UnimplementedSpeakerServer) mustEmbedUnimplementedSpeakerServer() {}

// UnsafeSpeakerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeakerServer will
// result in compilation errors.
type UnsafeSpeakerServer interface {
	mustEmbedUnimplementedSpeakerServer()
}

func RegisterSpeakerServer(s grpc.ServiceRegistrar, srv SpeakerServer) {
	s.RegisterService(&Speaker_ServiceDesc, srv)
}

func _Speaker_Speak_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeakerServer).Speak(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interceptor.Speaker/Speak",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeakerServer).Speak(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Speaker_ServiceDesc is the grpc.ServiceDesc for Speaker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Speaker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "interceptor.Speaker",
	HandlerType: (*SpeakerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Speak",
			Handler:    _Speaker_Speak_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "speaker.proto",
}
