// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: discover.proto

package discover

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscoverDemoClient is the client API for DiscoverDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoverDemoClient interface {
	Discover(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type discoverDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoverDemoClient(cc grpc.ClientConnInterface) DiscoverDemoClient {
	return &discoverDemoClient{cc}
}

func (c *discoverDemoClient) Discover(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/stream.DiscoverDemo/discover", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoverDemoServer is the server API for DiscoverDemo service.
// All implementations must embed UnimplementedDiscoverDemoServer
// for forward compatibility
type DiscoverDemoServer interface {
	Discover(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedDiscoverDemoServer()
}

// UnimplementedDiscoverDemoServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoverDemoServer struct {
}

func (UnimplementedDiscoverDemoServer) Discover(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedDiscoverDemoServer) mustEmbedUnimplementedDiscoverDemoServer() {}

// UnsafeDiscoverDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoverDemoServer will
// result in compilation errors.
type UnsafeDiscoverDemoServer interface {
	mustEmbedUnimplementedDiscoverDemoServer()
}

func RegisterDiscoverDemoServer(s grpc.ServiceRegistrar, srv DiscoverDemoServer) {
	s.RegisterService(&DiscoverDemo_ServiceDesc, srv)
}

func _DiscoverDemo_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoverDemoServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.DiscoverDemo/discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoverDemoServer).Discover(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscoverDemo_ServiceDesc is the grpc.ServiceDesc for DiscoverDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscoverDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.DiscoverDemo",
	HandlerType: (*DiscoverDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "discover",
			Handler:    _DiscoverDemo_Discover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discover.proto",
}
