// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: safety.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SafetyDemoClient is the client API for SafetyDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SafetyDemoClient interface {
	Secret(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type safetyDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewSafetyDemoClient(cc grpc.ClientConnInterface) SafetyDemoClient {
	return &safetyDemoClient{cc}
}

func (c *safetyDemoClient) Secret(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/safety.SafetyDemo/Secret", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SafetyDemoServer is the server API for SafetyDemo service.
// All implementations must embed UnimplementedSafetyDemoServer
// for forward compatibility
type SafetyDemoServer interface {
	Secret(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedSafetyDemoServer()
}

// UnimplementedSafetyDemoServer must be embedded to have forward compatible implementations.
type UnimplementedSafetyDemoServer struct {
}

func (UnimplementedSafetyDemoServer) Secret(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Secret not implemented")
}
func (UnimplementedSafetyDemoServer) mustEmbedUnimplementedSafetyDemoServer() {}

// UnsafeSafetyDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SafetyDemoServer will
// result in compilation errors.
type UnsafeSafetyDemoServer interface {
	mustEmbedUnimplementedSafetyDemoServer()
}

func RegisterSafetyDemoServer(s grpc.ServiceRegistrar, srv SafetyDemoServer) {
	s.RegisterService(&SafetyDemo_ServiceDesc, srv)
}

func _SafetyDemo_Secret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SafetyDemoServer).Secret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/safety.SafetyDemo/Secret",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SafetyDemoServer).Secret(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// SafetyDemo_ServiceDesc is the grpc.ServiceDesc for SafetyDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SafetyDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "safety.SafetyDemo",
	HandlerType: (*SafetyDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Secret",
			Handler:    _SafetyDemo_Secret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "safety.proto",
}
