// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: gateway.proto

package gateway

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GatewayDemoClient is the client API for GatewayDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayDemoClient interface {
	Gate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error)
}

type gatewayDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayDemoClient(cc grpc.ClientConnInterface) GatewayDemoClient {
	return &gatewayDemoClient{cc}
}

func (c *gatewayDemoClient) Gate(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Reply, error) {
	out := new(Reply)
	err := c.cc.Invoke(ctx, "/stream.GatewayDemo/Gate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayDemoServer is the server API for GatewayDemo service.
// All implementations must embed UnimplementedGatewayDemoServer
// for forward compatibility
type GatewayDemoServer interface {
	Gate(context.Context, *Request) (*Reply, error)
	mustEmbedUnimplementedGatewayDemoServer()
}

// UnimplementedGatewayDemoServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayDemoServer struct {
}

func (UnimplementedGatewayDemoServer) Gate(context.Context, *Request) (*Reply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Gate not implemented")
}
func (UnimplementedGatewayDemoServer) mustEmbedUnimplementedGatewayDemoServer() {}

// UnsafeGatewayDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayDemoServer will
// result in compilation errors.
type UnsafeGatewayDemoServer interface {
	mustEmbedUnimplementedGatewayDemoServer()
}

func RegisterGatewayDemoServer(s grpc.ServiceRegistrar, srv GatewayDemoServer) {
	s.RegisterService(&GatewayDemo_ServiceDesc, srv)
}

func _GatewayDemo_Gate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayDemoServer).Gate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stream.GatewayDemo/Gate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayDemoServer).Gate(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayDemo_ServiceDesc is the grpc.ServiceDesc for GatewayDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.GatewayDemo",
	HandlerType: (*GatewayDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Gate",
			Handler:    _GatewayDemo_Gate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway.proto",
}
